---
- hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Update APT package index and upgrade
      apt:
        upgrade: yes
        update_cache: yes
      become: true

    - name: Reboot the system
      reboot:
        reboot_timeout: 300
        post_reboot_delay: 60
      become: true
      ignore_errors: true
